version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/project.lcov

workflows:
  build_and_test:
    jobs:
      - build
